server:
  port: 8003

#eureka服务提供方(provider)配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

#开启hystrix断路器
feign:
  hystrix:
    enabled: true
#设置读取超时时间
ribbon.ReadTimeout: 5000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

#spring配置
spring:
  application:
    name: forum #服务名称，在eureka注册中心显示

  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/forum
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  #redis配置
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 1024
      max-idle: 200

#mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml #mapper路径

#日志级别
logging:
  level:
    root: debug

########自定义配置项########
billon:
  forum:
    sid: c9ee5ae61f263aa5f6d243f3153bc76e #论坛模块内部服务id